//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Pravesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic
    {
        public int academic_id { get; set; }
        public string std_id { get; set; }
        public string ssc_year { get; set; }
        public string ssc_school { get; set; }
        public string ssc_board { get; set; }
        public string ssc_rno { get; set; }
        public Nullable<int> ssc_marks { get; set; }
        public string hsc_year { get; set; }
        public string hsc_school { get; set; }
        public string hsc_board { get; set; }
        public string hsc_rno { get; set; }
        public Nullable<int> hsc_marks { get; set; }
        public Nullable<int> competitive_exam_id { get; set; }
        public string competitive_exam_year { get; set; }
        public string competitive_exam_rno { get; set; }
        public Nullable<int> competitive_exam_marks { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
