//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Pravesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allotment
    {
        public string std_id { get; set; }
        public Nullable<int> alloted_choice_id { get; set; }
        public Nullable<int> confirm_status { get; set; }
        public Nullable<int> preference_no { get; set; }
        public Nullable<int> round_no { get; set; }
    
        public virtual StudentDetail StudentDetail { get; set; }
        public virtual Available_Choice Available_Choice { get; set; }
    }
}
