//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Pravesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Available_Choice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Available_Choice()
        {
            this.Allotments = new HashSet<Allotment>();
            this.Student_Choice = new HashSet<Student_Choice>();
        }
    
        public int choice_id { get; set; }
        public Nullable<int> branch_id { get; set; }
        public Nullable<int> college_id { get; set; }
        public Nullable<int> program_id { get; set; }
        public Nullable<int> gen { get; set; }
        public Nullable<int> obc { get; set; }
        public Nullable<int> sc { get; set; }
        public Nullable<int> st { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allotment> Allotments { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual College College { get; set; }
        public virtual Program Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Choice> Student_Choice { get; set; }
    }
}
