//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Pravesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class College_Program
    {
        public int college_id { get; set; }
        public int program_id { get; set; }
        public Nullable<int> reference_no { get; set; }
    
        public virtual College College { get; set; }
        public virtual Program Program { get; set; }
    }
}
