//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Pravesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int seat_id { get; set; }
        public Nullable<int> gen { get; set; }
        public Nullable<int> sc { get; set; }
        public Nullable<int> st { get; set; }
        public Nullable<int> obc { get; set; }
    }
}
