//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Pravesh
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentDetail()
        {
            this.Academics = new HashSet<Academic>();
            this.Student_Choice = new HashSet<Student_Choice>();
        }
    
        public string std_id { get; set; }
        public string std_name { get; set; }
        public Nullable<int> std_category { get; set; }
        public string username { get; set; }
        public Nullable<int> academic_id { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string contact_no { get; set; }
        public string email_id { get; set; }
        public Nullable<int> fees_paid { get; set; }
        public Nullable<int> rank { get; set; }
        public string pin { get; set; }
        public Nullable<int> program { get; set; }
        public Nullable<int> verified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academic> Academics { get; set; }
        public virtual Allotment Allotment { get; set; }
        public virtual Category Category { get; set; }
        public virtual Login Login { get; set; }
        public virtual Program Program1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Choice> Student_Choice { get; set; }
    }
}
